"""
Multi-Index Executor for Natural Language Query Processing

Executes multi-index queries with context filtering, result merging, and
parallel execution support. Implements the execution layer for query plans
generated by QueryPlanner.

Based on: docs/enterprise-nlq-multi-index-analysis.md Phase 4
Updated: 2026-04-21 - Integrated EntityRegistry for consistent repository lookup
"""

import asyncio
import logging
import time
from typing import Any, Dict, List, Optional, Set, Tuple, Union

from app.db.repositories.api_repository import APIRepository
from app.db.repositories.compliance_repository import ComplianceRepository
from app.db.repositories.gateway_repository import GatewayRepository
from app.db.repositories.metrics_repository import MetricsRepository
from app.db.repositories.prediction_repository import PredictionRepository
from app.db.repositories.recommendation_repository import RecommendationRepository
from app.db.repositories.transactional_log_repository import TransactionalLogRepository
from app.db.repositories.vulnerability_repository import VulnerabilityRepository
from app.models.query import (
    ExecutionStrategy,
    IndexQuery,
    QueryPlan,
    QueryResults,
)
from app.services.query.context_manager import ContextManager
from app.services.query.entity_registry import EntityRegistry

logger = logging.getLogger(__name__)


class MultiIndexExecutor:
    """Executes multi-index queries with context filtering and result merging.
    
    Handles execution of query plans that span multiple OpenSearch indices,
    applying context filters from session history, executing queries in
    optimal order, and merging results.
    
    Features:
    - Single-index query execution
    - Sequential multi-index execution with filtering
    - Parallel multi-index execution
    - Nested query execution for complex relationships
    - Context-aware filtering from session history
    - Result merging and deduplication
    - Comprehensive error handling and recovery
    - Performance tracking and optimization
    
    Example:
        >>> executor = MultiIndexExecutor(repositories, context_manager)
        >>> results = await executor.execute_plan(query_plan)
        >>> # Results contain merged data from all indices
    """
    
    def __init__(
        self,
        api_repository: APIRepository,
        gateway_repository: GatewayRepository,
        metrics_repository: MetricsRepository,
        prediction_repository: PredictionRepository,
        recommendation_repository: RecommendationRepository,
        compliance_repository: ComplianceRepository,
        vulnerability_repository: VulnerabilityRepository,
        transactional_log_repository: TransactionalLogRepository,
        context_manager: Optional[ContextManager] = None,
    ):
        """Initialize the multi-index executor.
        
        Args:
            api_repository: Repository for API operations
            gateway_repository: Repository for gateway operations
            metrics_repository: Repository for metrics operations
            prediction_repository: Repository for prediction operations
            recommendation_repository: Repository for recommendation operations
            compliance_repository: Repository for compliance operations
            vulnerability_repository: Repository for vulnerability operations
            transactional_log_repository: Repository for transaction log operations
            context_manager: Optional context manager for session context
        """
        self.api_repo = api_repository
        self.gateway_repo = gateway_repository
        self.metrics_repo = metrics_repository
        self.prediction_repo = prediction_repository
        self.recommendation_repo = recommendation_repository
        self.compliance_repo = compliance_repository
        self.vulnerability_repo = vulnerability_repository
        self.transactional_log_repo = transactional_log_repository
        self.context_manager = context_manager
        
        # Repository mapping for dynamic lookup (using EntityRegistry)
        self._repo_map = self._build_repo_map()
        
        logger.info("MultiIndexExecutor initialized")
    
    def _build_repo_map(self) -> Dict[str, Union[
        APIRepository,
        GatewayRepository,
        MetricsRepository,
        PredictionRepository,
        RecommendationRepository,
        ComplianceRepository,
        VulnerabilityRepository,
        TransactionalLogRepository
    ]]:
        """Build repository mapping using EntityRegistry."""
        repo_map: Dict[str, Union[
            APIRepository,
            GatewayRepository,
            MetricsRepository,
            PredictionRepository,
            RecommendationRepository,
            ComplianceRepository,
            VulnerabilityRepository,
            TransactionalLogRepository
        ]] = {}
        
        # Map each entity's index to its repository
        for entity_type in EntityRegistry.get_all_entity_types():
            index = EntityRegistry.get_index(entity_type)
            if not index:
                continue
            
            # Map entity type to repository
            if entity_type == "api":
                repo_map[index] = self.api_repo
            elif entity_type == "gateway":
                repo_map[index] = self.gateway_repo
            elif entity_type == "metric":
                # Metrics use multiple time-bucketed indices
                repo_map[index] = self.metrics_repo
                repo_map["api-metrics-1m"] = self.metrics_repo
                repo_map["api-metrics-5m"] = self.metrics_repo
                repo_map["api-metrics-1h"] = self.metrics_repo
                repo_map["api-metrics-1d"] = self.metrics_repo
            elif entity_type == "prediction":
                repo_map[index] = self.prediction_repo
            elif entity_type == "recommendation":
                repo_map[index] = self.recommendation_repo
            elif entity_type == "compliance":
                repo_map[index] = self.compliance_repo
            elif entity_type == "vulnerability":
                repo_map[index] = self.vulnerability_repo
            elif entity_type == "transaction":
                repo_map[index] = self.transactional_log_repo
        
        return repo_map
    
    async def execute_plan(self, plan: QueryPlan) -> QueryResults:
        """Execute a query plan and return merged results.
        
        Args:
            plan: Query execution plan
            
        Returns:
            Merged query results from all indices
            
        Raises:
            ValueError: If plan is invalid
            RuntimeError: If execution fails
        """
        start_time = time.time()
        
        try:
            logger.info(
                f"Executing query plan: strategy={plan.strategy}, "
                f"indices={len(plan.index_queries)}"
            )
            
            # Execute based on strategy
            if plan.strategy == ExecutionStrategy.SINGLE_INDEX:
                results = await self._execute_single_index(plan)
            elif plan.strategy == ExecutionStrategy.SEQUENTIAL:
                results = await self._execute_sequential(plan)
            elif plan.strategy == ExecutionStrategy.PARALLEL:
                results = await self._execute_parallel(plan)
            elif plan.strategy == ExecutionStrategy.NESTED:
                results = await self._execute_nested(plan)
            else:
                raise ValueError(f"Unknown execution strategy: {plan.strategy}")
            
            # Calculate execution time
            execution_time = int((time.time() - start_time) * 1000)
            results.execution_time = execution_time
            
            logger.info(
                f"Query plan executed successfully: "
                f"results={results.count}, time={execution_time}ms"
            )
            
            return results
            
        except Exception as e:
            execution_time = int((time.time() - start_time) * 1000)
            logger.error(f"Query plan execution failed: {e}", exc_info=True)
            
            # Return empty results with error information
            return QueryResults(
                data=[],
                count=0,
                execution_time=execution_time,
                aggregations={"error": str(e)}
            )
    
    async def _execute_single_index(self, plan: QueryPlan) -> QueryResults:
        """Execute a single-index query.
        
        Args:
            plan: Query plan with single index query
            
        Returns:
            Query results
        """
        if len(plan.index_queries) != 1:
            raise ValueError("Single index strategy requires exactly one index query")
        
        index_query = plan.index_queries[0]
        
        # Apply context filters
        filtered_query = self._apply_context_filters(
            index_query,
            plan.context_filters
        )
        
        # Execute query
        results = await self._execute_index_query(filtered_query)
        
        return results
    
    async def _execute_sequential(self, plan: QueryPlan) -> QueryResults:
        """Execute queries sequentially with result filtering.
        
        Each query uses results from previous queries to filter its results.
        
        Args:
            plan: Query plan with sequential execution
            
        Returns:
            Merged query results
        """
        all_results: List[Dict[str, Any]] = []
        previous_results: Dict[str, List[Dict[str, Any]]] = {}
        
        for index_query in plan.index_queries:
            # Apply context filters from plan
            filtered_query = self._apply_context_filters(
                index_query,
                plan.context_filters
            )
            
            # Apply filters from previous query results
            if index_query.depends_on:
                filtered_query = self._apply_dependency_filters(
                    filtered_query,
                    previous_results,
                    index_query.depends_on
                )
            
            # Execute query
            try:
                results = await self._execute_index_query(filtered_query)
                
                # Store results for next query
                previous_results[index_query.index] = results.data
                
                # Accumulate results
                all_results.extend(results.data)
                
                logger.debug(
                    f"Sequential query executed: index={index_query.index}, "
                    f"results={len(results.data)}"
                )
                
            except Exception as e:
                logger.error(
                    f"Sequential query failed for {index_query.index}: {e}",
                    exc_info=True
                )
                # Continue with next query even if one fails
                continue
        
        # Merge and deduplicate results
        merged_results = self._merge_results(all_results, plan.requires_join)
        
        return QueryResults(
            data=merged_results,
            count=len(merged_results),
            execution_time=0,  # Will be set by caller
            aggregations=None
        )
    
    async def _execute_parallel(self, plan: QueryPlan) -> QueryResults:
        """Execute queries in parallel and merge results.
        
        All queries execute simultaneously for maximum performance.
        
        Args:
            plan: Query plan with parallel execution
            
        Returns:
            Merged query results
        """
        # Create tasks for all queries
        tasks = []
        for index_query in plan.index_queries:
            # Apply context filters
            filtered_query = self._apply_context_filters(
                index_query,
                plan.context_filters
            )
            
            # Create execution task
            task = self._execute_index_query(filtered_query)
            tasks.append(task)
        
        # Execute all queries in parallel
        try:
            results_list = await asyncio.gather(*tasks, return_exceptions=True)
        except Exception as e:
            logger.error(f"Parallel execution failed: {e}", exc_info=True)
            return QueryResults(
                data=[],
                count=0,
                execution_time=0,
                aggregations={"error": str(e)}
            )
        
        # Collect successful results
        all_results: List[Dict[str, Any]] = []
        for i, result in enumerate(results_list):
            if isinstance(result, Exception):
                logger.error(
                    f"Parallel query failed for {plan.index_queries[i].index}: {result}"
                )
                continue
            
            if isinstance(result, QueryResults):
                all_results.extend(result.data)
                logger.debug(
                    f"Parallel query executed: index={plan.index_queries[i].index}, "
                    f"results={len(result.data)}"
                )
        
        # Merge and deduplicate results
        merged_results = self._merge_results(all_results, plan.requires_join)
        
        return QueryResults(
            data=merged_results,
            count=len(merged_results),
            execution_time=0,  # Will be set by caller
            aggregations=None
        )
    
    async def _execute_nested(self, plan: QueryPlan) -> QueryResults:
        """Execute nested queries for complex multi-hop relationships.
        
        Uses results from each query to filter the next query in the chain.
        
        Args:
            plan: Query plan with nested execution
            
        Returns:
            Query results from final query in chain
        """
        current_results: Optional[QueryResults] = None
        accumulated_filters: Dict[str, Set[str]] = {}
        
        for index_query in plan.index_queries:
            # Apply context filters from plan
            filtered_query = self._apply_context_filters(
                index_query,
                plan.context_filters
            )
            
            # Apply accumulated filters from previous queries
            if accumulated_filters:
                filtered_query = self._apply_accumulated_filters(
                    filtered_query,
                    accumulated_filters
                )
            
            # Execute query
            try:
                current_results = await self._execute_index_query(filtered_query)
                
                # Extract entity IDs for next query
                if current_results.data and index_query.join_fields:
                    for source_field, target_field in index_query.join_fields.items():
                        ids = self._extract_field_values(
                            current_results.data,
                            source_field
                        )
                        if ids:
                            if target_field not in accumulated_filters:
                                accumulated_filters[target_field] = set()
                            accumulated_filters[target_field].update(ids)
                
                logger.debug(
                    f"Nested query executed: index={index_query.index}, "
                    f"results={len(current_results.data)}"
                )
                
            except Exception as e:
                logger.error(
                    f"Nested query failed for {index_query.index}: {e}",
                    exc_info=True
                )
                # Return empty results if any query in chain fails
                return QueryResults(
                    data=[],
                    count=0,
                    execution_time=0,
                    aggregations={"error": str(e)}
                )
        
        # Return results from final query
        return current_results or QueryResults(
            data=[],
            count=0,
            execution_time=0,
            aggregations=None
        )
    
    def _apply_context_filters(
        self,
        index_query: IndexQuery,
        context_filters: Dict[str, Any]
    ) -> IndexQuery:
        """Apply context filters to an index query.
        
        Args:
            index_query: Original index query
            context_filters: Context filters from session
            
        Returns:
            Modified index query with context filters applied
        """
        if not context_filters:
            return index_query
        
        # Create a copy of the query
        query_dsl = index_query.query_dsl.copy()
        
        # Get existing must clauses
        if "query" not in query_dsl:
            query_dsl["query"] = {"bool": {"must": []}}
        elif "bool" not in query_dsl["query"]:
            # Wrap existing query in bool
            existing_query = query_dsl["query"]
            query_dsl["query"] = {"bool": {"must": [existing_query]}}
        elif "must" not in query_dsl["query"]["bool"]:
            query_dsl["query"]["bool"]["must"] = []
        
        must_clauses = query_dsl["query"]["bool"]["must"]
        if not isinstance(must_clauses, list):
            must_clauses = [must_clauses]
            query_dsl["query"]["bool"]["must"] = must_clauses
        
        # Add context filters
        for field, value in context_filters.items():
            if isinstance(value, list):
                must_clauses.append({"terms": {field: value}})
            else:
                must_clauses.append({"term": {field: value}})
        
        # Return modified query
        return IndexQuery(
            index=index_query.index,
            query_dsl=query_dsl,
            filters=index_query.filters,
            required_fields=index_query.required_fields,
            join_fields=index_query.join_fields,
            depends_on=index_query.depends_on
        )
    
    def _apply_dependency_filters(
        self,
        index_query: IndexQuery,
        previous_results: Dict[str, List[Dict[str, Any]]],
        dependencies: List[str]
    ) -> IndexQuery:
        """Apply filters from dependent query results.
        
        Args:
            index_query: Index query to filter
            previous_results: Results from previous queries
            dependencies: List of dependent indices
            
        Returns:
            Modified index query with dependency filters
        """
        if not dependencies or not previous_results:
            return index_query
        
        # Extract entity IDs from dependent results
        dependency_filters: Dict[str, Set[str]] = {}
        
        for dep_index in dependencies:
            if dep_index not in previous_results:
                continue
            
            dep_results = previous_results[dep_index]
            
            # Extract join field values
            for source_field, target_field in index_query.join_fields.items():
                ids = self._extract_field_values(dep_results, source_field)
                if ids:
                    if target_field not in dependency_filters:
                        dependency_filters[target_field] = set()
                    dependency_filters[target_field].update(ids)
        
        # Apply filters
        return self._apply_accumulated_filters(index_query, dependency_filters)
    
    def _apply_accumulated_filters(
        self,
        index_query: IndexQuery,
        accumulated_filters: Dict[str, Set[str]]
    ) -> IndexQuery:
        """Apply accumulated filters from previous queries.
        
        Args:
            index_query: Index query to filter
            accumulated_filters: Accumulated filters by field
            
        Returns:
            Modified index query with accumulated filters
        """
        if not accumulated_filters:
            return index_query
        
        # Convert to context filters format
        context_filters = {
            field: list(values)
            for field, values in accumulated_filters.items()
        }
        
        return self._apply_context_filters(index_query, context_filters)
    
    def _extract_field_values(
        self,
        results: List[Dict[str, Any]],
        field: str
    ) -> Set[str]:
        """Extract unique values for a field from results.
        
        Args:
            results: List of result documents
            field: Field name to extract
            
        Returns:
            Set of unique field values
        """
        values: Set[str] = set()
        
        for result in results:
            if field in result and result[field]:
                value = result[field]
                if isinstance(value, list):
                    values.update(str(v) for v in value)
                else:
                    values.add(str(value))
        
        return values
    
    async def _execute_index_query(self, index_query: IndexQuery) -> QueryResults:
        """Execute a query against a single index.
        
        Args:
            index_query: Index query to execute
            
        Returns:
            Query results
            
        Raises:
            ValueError: If index not found
            RuntimeError: If query execution fails
        """
        start_time = time.time()
        
        # Get repository for index
        repo = self._get_repository(index_query.index)
        if not repo:
            raise ValueError(f"No repository found for index: {index_query.index}")
        
        try:
            # Execute search
            results, total = repo.search(
                index_query.query_dsl.get("query", {"match_all": {}}),
                size=100  # Configurable limit
            )
            
            # Serialize results using LLM-optimized format
            data = self._serialize_results(results, index_query.index)
            
            execution_time = int((time.time() - start_time) * 1000)
            
            # Use len(data) for count to reflect actual results returned
            # total from OpenSearch may differ due to size limit or serialization
            return QueryResults(
                data=data,
                count=len(data),
                execution_time=execution_time,
                aggregations=None
            )
            
        except Exception as e:
            logger.error(
                f"Query execution failed for {index_query.index}: {e}",
                exc_info=True
            )
            raise RuntimeError(f"Query execution failed: {e}") from e
    
    def _get_repository(self, index: str):
        """Get repository for an index.
        
        Args:
            index: Index name (may include wildcards)
            
        Returns:
            Repository instance or None
        """
        # Direct lookup
        if index in self._repo_map:
            return self._repo_map[index]
        
        # Pattern matching for metric indices
        if index.startswith("api-metrics-"):
            return self.metrics_repo
        
        return None
    
    def _serialize_results(
        self,
        results: List[Any],
        index: str
    ) -> List[Dict[str, Any]]:
        """Serialize results using LLM-optimized format.
        
        Args:
            results: Raw results from repository
            index: Index name
            
        Returns:
            Serialized results
        """
        serialized = []
        
        for result in results:
            # Use LLM-optimized serialization if available
            if hasattr(result, 'to_llm_dict'):
                serialized.append(result.to_llm_dict())
            elif hasattr(result, 'model_dump'):
                serialized.append(result.model_dump(mode="json"))
            elif hasattr(result, 'dict'):
                serialized.append(result.dict())
            else:
                # Fallback to dict conversion
                serialized.append(dict(result))
        
        return serialized
    
    def _merge_results(
        self,
        results: List[Dict[str, Any]],
        requires_join: bool
    ) -> List[Dict[str, Any]]:
        """Merge and deduplicate results from multiple indices.
        
        Args:
            results: List of result documents
            requires_join: Whether results need joining
            
        Returns:
            Merged and deduplicated results
        """
        if not results:
            return []
        
        if not requires_join:
            # Simple deduplication by ID
            seen_ids: Set[str] = set()
            merged = []
            
            for result in results:
                result_id = result.get('id')
                if result_id and result_id not in seen_ids:
                    seen_ids.add(result_id)
                    merged.append(result)
                elif not result_id:
                    # Include results without IDs
                    merged.append(result)
            
            return merged
        
        # Join-based merging (group by common fields)
        # This is a simplified implementation - can be enhanced based on join strategy
        return results


# Made with Bob